name: ocean_card
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
     sdk: ^3.9.0-97.0.dev

dependencies:
     bloc: ^9.0.0
     cloud_firestore: ^6.0.3
     dart_firebase_admin: ^0.4.1
     equatable: ^2.0.7
     firebase_auth: ^6.1.1
     firebase_core: ^4.2.0
     flutter:
          sdk: flutter
     flutter_bloc: ^9.1.1
     flutter_localizations:
          sdk: flutter
     go_router: ^16.2.4
     google_fonts: ^6.3.2
     shared_preferences: ^2.5.3
     flutter_svg: ^2.1.0
     intl_phone_field: ^3.2.0
     country_pickers: ^3.0.1

dev_dependencies:
     flutter_test:
          sdk: flutter
     flutter_lints: ^6.0.0
     flutter_launcher_icons: ^0.14.3

flutter:
     uses-material-design: true
     assets:
          - assets/

flutter_launcher_icons:
     image_path: "assets/icon.png"
     android: true
     ios: true
     web:
          generate: true
          image_path: "assets/icon.png"
          background_color: "#ffffff"
          theme_color: "#000000"
     windows:
          generate: true
          image_path: "assets/icon.png"
          icon_size: 48
     macos:
          generate: true
          image_path: "assets/icon.png"
