name: ocean_card
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
     sdk: ^3.9.0-97.0.dev

dependencies:
     bloc: ^9.0.0
     cloud_firestore: ^5.6.7
     dart_firebase_admin: ^0.4.1
     equatable: ^2.0.7
     firebase_auth: ^5.5.3
     firebase_core: ^3.13.0
     flutter:
          sdk: flutter
     flutter_bloc: ^9.1.1
     flutter_localizations:
          sdk: flutter
     go_router: ^15.1.2
     google_fonts: ^6.2.1
     shared_preferences: ^2.5.3
     flutter_svg: ^2.1.0

dev_dependencies:
     flutter_test:
          sdk: flutter
     flutter_lints: ^5.0.0

flutter:
     uses-material-design: true
     assets:
          - assets/
